sudo: required
services:
  - docker

before_install:
  - docker build -t ssood/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ssood/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region:  "us-west-2"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-660500821562"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY